#Travis 설정 파일

#관리자 권한 갖기
sudo: required

#언어(플랫폼) 선택
language: generic

#도커 환경 구성
services:
  - docker

#스크립트를 실행할 수 있는 환경 구성
before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t sin9173/docker-react-app -f Dockerfile.dev .

#실행할 스크립트 (테스트) Travis-CI 사용할 경우 CI=true 옵션
#coverage : 상세로그 출력
script:
  - docker run -e CI=true sin9173/docker-react-app npm run test -- --coverage


#배포에 관한 설정
deploy:
  #외부서비스 표시 (S3, elasticbeanstalk, firebase 등)
  provider: elasticbeanstalk

  #현재 사용하고 있는 AWS의 서비스가 위치하고 있는 물리적 장소 (us-east-2, ap-northeast2 등 리전에따라 달라짐, AWS에서 확인)
  region: "us-east-2"

  #생성된 어플리케이션의 이름
  app: "docker-react-app"

  #환경의 이름
  env: "Dockerreactapp-env"

  #S3 버킷 이름 (travis-ci에서 가지고 있는 파일을 압축해서 S3에 보냄)
  bucket_name: "elasticbeanstalk-us-east-2-512440888874"

  #어플리케이션의 이름과 동일
  bucket_path: "docker-react-app"

  on:
    #AWS에 배포할 브랜치
    branch: master
  #인증정보 (Travis-ci에서 설정한 환경변수 가져오기)
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY    


#테스트 성공 후 동작
after_success:
  - echo "Test success"
